---
driver:
  name: docker 
  socket: <%= ENV['DOCKER_HOST'] %>
driver_config:
  require_chef_omnibus: true
busser:
  sudo: true

platforms:
  - name: ubuntu-14.04
    driver_config:
      image: ubuntu:14.04 

suites:
- name: default
  run_list: 
    - "recipe[review::default]"
  attributes:
